### ISSUE TITLE
Include a standalone demo

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_nodejs_app#9]
Add a notebook to this repo and instructions in the README about how to bring up an instance of the node app and have the notebook run as a dashboard. You'll probably want to use Docker because you'll need all of:

1. The notebook on disk
2. The node app
3. The kernel gateway
4. The kernel used in the notebook
5. Any other dependencies (matplotlib, node, npm, ...)

You could put all this in a single Docker container and launch two services for the demo (the node app + the kernel gateway). Or you could do a small docker-compose.yml with the kernel gateway running in one container (hopefully based on jupyter/docker-stacks#42 when it lands) and the node app in another.

The goal here is to show how the dashboard backend works independently of the bundler and the dashboard layout extension. Later, we can expand the README to link to those to paint the full picture.

---

**TODO**
* [x] Create standalone demo notebook
* [x] Create Docker container
* [x] Replace `jupyter-incubator/all-spark-kernels` image with the `minimal-kernel` image.
* [ ] npm install `jupyter-js-widgets` instead of building it from source 
* [x] Use docker `link` command to link together the containers, instead of querying IP of kernel gateway container.

**Comment by jhpedemonte** [comment]
Pushed changes to build Docker containers. But this is still not complete. Added some remaining todos in the description.

**Comment by parente** [comment]
Minimal kernel image pushed to Docker Hub in jupyter/docker-stacks#42.

**Comment by parente** [comment]
This one is waiting on jupyter-js-widgets to have a stable npm release so that we can update the dockerfiles and not have to pull everything from git source.

**Comment by parente** [comment]
Marking this one closed. We don't need to wait for a stable release of jupyter-js-widgets to move forward. We'll have one issue where we track moving to stable ipywidgets/jupyter-js-widgets releases when they're available.
